export const regions = [
  {
    id: 1,
    name: "Xorazm",
    regions: [
      {
        id: 1,
        name: "Bog'ot",
        centre: "Bog'ot",
        langitude: "41.325935",
        latitude: "60.836552",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Bogʻot tumani",
      },
      {
        id: 2,
        name: "Gurlan",
        centre: "Gurlan",
        langitude: "41.880465",
        latitude: "60.354624",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Gurlan tumani",
      },
      {
        id: 3,
        name: "Xonqa",
        centre: "Xonqa",
        langitude: "41.486231",
        latitude: "60.834441",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Xonqa tumani",
      },
      {
        id: 4,
        name: "Hazorasp",
        centre: "Hazorasp",
        langitude: "41.284262",
        latitude: "61.140964",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Hazorasp tumani",
      },
      {
        id: 5,
        name: "Xiva",
        centre: "Xiva",
        langitude: "41.384443",
        latitude: "60.361864",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Xiva",
      },
      {
        id: 6,
        name: "Qo'shko'pir",
        centre: "Qo'shko'pir",
        langitude: "41.503974",
        latitude: "60.261981",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Qoʻshkoʻpir tumani",
      },
      {
        id: 7,
        name: "Shovot",
        centre: "Shovot",
        langitude: "41.691022",
        latitude: "60.255225",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Shovot tumani",
      },
      {
        id: 8,
        name: "Urganch",
        centre: "Qorovul",
        langitude: "41.549689",
        latitude: "60.631377",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Urganch",
      },
      {
        id: 9,
        name: "Yangiariq",
        centre: "Yangiariq",
        langitude: "41.325265",
        latitude: "60.585805",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Yangiariq tumani",
      },
      {
        id: 10,
        name: "Yangibozor",
        centre: "Yangibozor",
        langitude: "41.729613",
        latitude: "60.489371",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Yangibozor tumani",
      },
      {
        id: 11,
        name: "Tuproqqal'a",
        centre: "Tuproqqal'a",
        langitude: "41.205986",
        latitude: "61.286033",
        addressLine: "Oʻzbekiston, Xorazm viloyati, Tuproqqalʼa tumani",
      },
    ],
    langitude: "41.433454",
    latitude: "60.615378",
    addressLine: "Oʻzbekiston, Xorazm viloyati",
  },
  {
    id: 2,
    name: "Navoiy",
    regions: [
      {
        id: 1,
        name: "Konimex",
        centre: "Konimex",
        langitude: "41.0589",
        latitude: "64.622457",
        addressLine: "Oʻzbekiston, Navoiy viloyati, Konimex tumani",
      },
      {
        id: 2,
        name: "Karmana",
        centre: "Karmana",
        langitude: "40.03813",
        latitude: "65.278452",
        addressLine: "Oʻzbekiston, Navoiy viloyati, Karmana tumani",
      },
      {
        id: 3,
        name: "Qiziltepa",
        centre: "Qiziltepa",
        langitude: "40.037487",
        latitude: "64.851366",
        addressLine:
          "Oʻzbekiston, Navoiy viloyati, Qiziltepa tumani, Qiziltepa",
      },
      {
        id: 4,
        name: "Xatirchi",
        centre: "Yangirabot",
        langitude: "40.191449",
        latitude: "65.943636",
        addressLine: "Oʻzbekiston, Navoiy viloyati, Xatirchi tumani",
      },
      {
        id: 5,
        name: "Navbahor",
        centre: "Beshrabot",
        langitude: "40.258971",
        latitude: "65.439645",
        addressLine: "Oʻzbekiston, Navoiy viloyati, Navbahor tumani",
      },
      {
        id: 6,
        name: "Nurota",
        centre: "Nurota",
        langitude: "40.564798",
        latitude: "65.693006",
        addressLine: "Oʻzbekiston, Navoiy viloyati, Nurota tumani, Nurota",
      },
      {
        id: 7,
        name: "Tomdi",
        centre: "Tomdibuloq",
        langitude: "42.052267",
        latitude: "65.243642",
        addressLine: "Oʻzbekiston, Navoiy viloyati, Tomdi tumani",
      },
      {
        id: 8,
        name: "Uchquduq",
        centre: "Uchquduq",
        langitude: "41.179658",
        latitude: "64.551364",
        addressLine: "Oʻzbekiston, A379",
      },
    ],
    langitude: "40.103086",
    latitude: "65.373961",
    addressLine: "Oʻzbekiston, Navoiy",
  },
  {
    id: 3,
    name: "Buxoro",
    regions: [
      {
        id: 1,
        name: "Olot",
        centre: "Olot",
        langitude: "39.413378",
        latitude: "63.802439",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Olot tumani, Olot",
      },
      {
        id: 2,
        name: "Buxoro",
        centre: "Galaosiyo",
        langitude: "39.767945",
        latitude: "64.421701",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Buxoro",
      },
      {
        id: 3,
        name: "G'ijduvon",
        centre: "G'ijduvon",
        langitude: "40.10279",
        latitude: "64.678467",
        addressLine:
          "Oʻzbekiston, Buxoro viloyati, Gʻijduvon tumani, Gʻijduvon",
      },
      {
        id: 4,
        name: "Jondor",
        centre: "Jondor",
        langitude: "39.92871",
        latitude: "63.668671",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Jondor tumani",
      },
      {
        id: 5,
        name: "Kogon",
        centre: "Kogon",
        langitude: "39.723523",
        latitude: "64.54716",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Kogon",
      },
      {
        id: 6,
        name: "Qorako'l",
        centre: "Qorako'l",
        langitude: "39.531409",
        latitude: "63.835452",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Qorakoʻl tumani, Qorakoʻl",
      },
      {
        id: 7,
        name: "Qorovulbozor",
        centre: "Qorovulbozor",
        langitude: "39.499938",
        latitude: "64.791071",
        addressLine:
          "Oʻzbekiston, Buxoro viloyati, Qorovulbozor tumani, Qorovulbozor",
      },
      {
        id: 8,
        name: "Peshku",
        centre: "Yangibozor",
        langitude: "40.591524",
        latitude: "63.39402",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Peshku tumani",
      },
      {
        id: 9,
        name: "Romitan",
        centre: "Romitan",
        langitude: "39.93315",
        latitude: "64.382652",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Romitan tumani, Romitan",
      },
      {
        id: 10,
        name: "Shofirkon",
        centre: "Shofirkon",
        langitude: "40.118268",
        latitude: "64.502586",
        addressLine:
          "Oʻzbekiston, Buxoro viloyati, Shofirkon tumani, Shofirkon",
      },
      {
        id: 11,
        name: "Vobkent",
        centre: "Vobkent",
        langitude: "39.78937",
        latitude: "64.416815",
        addressLine: "Oʻzbekiston, Buxoro viloyati, Buxoro, Vobkent ko'chasi",
      },
    ],
    langitude: "39.767945",
    latitude: "64.421701",
    addressLine: "Oʻzbekiston, Buxoro viloyati, Buxoro",
  },
  {
    id: 4,
    name: "Samarqand",
    regions: [
      {
        id: 1,
        name: "Bulung'ur",
        centre: "Bulung'ur",
        langitude: "39.762947",
        latitude: "67.2729",
        addressLine:
          "Oʻzbekiston, Samarqand viloyati, Bulungʻur tumani, Bulungʻur",
      },
      {
        id: 2,
        name: "Ishtixon",
        centre: "Ishtixon",
        langitude: "39.964857",
        latitude: "66.487252",
        addressLine:
          "Oʻzbekiston, Samarqand viloyati, Ishtixon tumani, Ishtixon",
      },
      {
        id: 3,
        name: "Jomboy",
        centre: "Jomboy",
        langitude: "39.69697",
        latitude: "67.096471",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Jomboy tumani, Jomboy",
      },
      {
        id: 4,
        name: "Kattaqo'rg'on",
        centre: "Payshanba",
        langitude: "39.903504",
        latitude: "66.265035",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Kattaqoʻrgʻon",
      },
      {
        id: 5,
        name: "Qo'shrabot",
        centre: "Qo'shrabot",
        langitude: "40.379515",
        latitude: "66.533389",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Qo'shrabot tumani",
      },
      {
        id: 6,
        name: "Narpay",
        centre: "Oqtosh",
        langitude: "39.933116",
        latitude: "65.982479",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Narpay tumani",
      },
      {
        id: 7,
        name: "Nurobod",
        centre: "Nurobod",
        langitude: "39.608295",
        latitude: "66.283289",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Nurobod tumani, Nurobod",
      },
      {
        id: 8,
        name: "Oqdaryo",
        centre: "Loyish",
        langitude: "39.973027",
        latitude: "66.50175",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Oqdaryo",
      },
      {
        id: 9,
        name: "Paxtachi",
        centre: "Ziyodin",
        langitude: "39.88525",
        latitude: "65.569111",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Paxtachi tumani",
      },
      {
        id: 10,
        name: "Payariq",
        centre: "Payariq",
        langitude: "39.990041",
        latitude: "66.846353",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Payariq tumani, Payariq",
      },
      {
        id: 11,
        name: "Pastdarg'om",
        centre: "Juma",
        langitude: "39.660431",
        latitude: "66.662297",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Pastdargʻom tumani",
      },
      {
        id: 12,
        name: "Samarqand",
        centre: "Gulobod",
        langitude: "39.654515",
        latitude: "66.968847",
        addressLine: "Oʻzbekiston, Samarqand",
      },
      {
        id: 13,
        name: "Toyloq",
        centre: "Toyloq",
        langitude: "39.570798",
        latitude: "67.150181",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Toyloq tumani",
      },
      {
        id: 14,
        name: "Urgut",
        centre: "Urgut",
        langitude: "39.408814",
        latitude: "67.243391",
        addressLine: "Oʻzbekiston, Samarqand viloyati, Urgut tumani, Urgut",
      },
    ],
    langitude: "39.654515",
    latitude: "66.968847",
    addressLine: "Oʻzbekiston, Samarqand",
  },
  {
    id: 5,
    name: "Qashqadaryo",
    regions: [
      {
        id: 1,
        name: "Chiroqchi",
        centre: "Chiroqchi",
        langitude: "39.03171",
        latitude: "66.572412",
        addressLine:
          "Oʻzbekiston, Qashqadaryo viloyati, Chiroqchi tumani, Chiroqchi",
      },
      {
        id: 2,
        name: "Dehqonobod",
        centre: "Karashina",
        langitude: "38.367509",
        latitude: "66.629814",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Dehqonobod tumani",
      },
      {
        id: 3,
        name: "G'uzor",
        centre: "G'uzor",
        langitude: "38.626751",
        latitude: "66.252558",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Gʻuzor",
      },
      {
        id: 4,
        name: "Qamashi",
        centre: "Qamashi",
        langitude: "38.812345",
        latitude: "66.480101",
        addressLine:
          "Oʻzbekiston, Qashqadaryo viloyati, Qamashi tumani, Qamashi",
      },
      {
        id: 5,
        name: "Qarshi",
        centre: "Beshkent",
        langitude: "38.84164",
        latitude: "65.789979",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Qarshi",
      },
      {
        id: 6,
        name: "Koson",
        centre: "Koson",
        langitude: "39.04156",
        latitude: "65.585352",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Koson tumani, Koson",
      },
      {
        id: 7,
        name: "Kasbi",
        centre: "Mug'lon",
        langitude: "38.893989",
        latitude: "65.453677",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Kasbi tumani",
      },
      {
        id: 8,
        name: "Kitob",
        centre: "Kitob",
        langitude: "39.118508",
        latitude: "66.874929",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Kitob tumani, Kitob",
      },
      {
        id: 9,
        name: "Mirishkor",
        centre: "Yangi Mirishkor",
        langitude: "38.819683",
        latitude: "64.977902",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Mirishkor tumani",
      },
      {
        id: 10,
        name: "Muborak",
        centre: "Muborak",
        langitude: "39.261236",
        latitude: "65.156811",
        addressLine:
          "Oʻzbekiston, Qashqadaryo viloyati, Muborak tumani, Muborak",
      },
      {
        id: 11,
        name: "Nishon",
        centre: "Yangi Nishon",
        langitude: "38.519305",
        latitude: "65.578031",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Nishon tumani",
      },
      {
        id: 12,
        name: "Shahrisabz",
        centre: "Shahrisabz",
        langitude: "39.060073",
        latitude: "66.829483",
        addressLine: "Oʻzbekiston, Qashqadaryo viloyati, Shahrisabz",
      },
      {
        id: 13,
        name: "Yakkabog'",
        centre: "Yakkabog'",
        langitude: "38.977346",
        latitude: "66.687881",
        addressLine:
          "Oʻzbekiston, Qashqadaryo viloyati, Yakkabogʻ tumani, Yakkabogʻ",
      },
    ],
    langitude: "38.681237",
    latitude: "66.130504",
    addressLine: "Oʻzbekiston, Qashqadaryo viloyati",
  },
  {
    id: 6,
    name: "Surxondaryo",
    regions: [
      {
        id: 1,
        name: "Angor",
        centre: "Angor",
        langitude: "37.435593",
        latitude: "67.221094",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Angor tumani",
      },
      {
        id: 2,
        name: "Boysun",
        centre: "Boysun",
        langitude: "38.208254",
        latitude: "67.207072",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Boysun tumani, Boysun",
      },
      {
        id: 3,
        name: "Denov",
        centre: "Denov",
        langitude: "38.274929",
        latitude: "67.89625",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Denov tumani, Denov",
      },
      {
        id: 4,
        name: "Jarqo'rg'on",
        centre: "Jarqo'rg'on",
        langitude: "37.508379",
        latitude: "67.413693",
        addressLine:
          "Oʻzbekiston, Surxondaryo viloyati, Jarqoʻrgʻon tumani, Jarqoʻrgʻon",
      },
      {
        id: 5,
        name: "Qiziriq",
        centre: "Sariq",
        langitude: "37.648587",
        latitude: "67.245151",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Qiziriq tumani",
      },
      {
        id: 6,
        name: "Qumqo'rg'on",
        centre: "Qumqo'rg'on",
        langitude: "37.825362",
        latitude: "67.591793",
        addressLine:
          "Oʻzbekiston, Surxondaryo viloyati, Qumqoʻrgʻon tumani, Qumqoʻrgʻon",
      },
      {
        id: 7,
        name: "Muzrabot",
        centre: "Xalqobod",
        langitude: "37.423099",
        latitude: "66.864104",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Muzrabot tumani",
      },
      {
        id: 8,
        name: "Oltinsoy",
        centre: "Qarluq",
        langitude: "38.181917",
        latitude: "67.733628",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Oltinsoy tumani",
      },
      {
        id: 9,
        name: "Sariosiyo",
        centre: "Sariosiyo",
        langitude: "38.732662",
        latitude: "67.801774",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Sariosiyo tumani",
      },
      {
        id: 10,
        name: "Sherobod",
        centre: "Sherobod",
        langitude: "37.675182",
        latitude: "67.016485",
        addressLine:
          "Oʻzbekiston, Surxondaryo viloyati, Sherobod tumani, Sherobod",
      },
      {
        id: 11,
        name: "Sho'rchi",
        centre: "Sho'rchi",
        langitude: "38.010959",
        latitude: "67.790599",
        addressLine:
          "Oʻzbekiston, Surxondaryo viloyati, Shoʻrchi tumani, Shoʻrchi",
      },
      {
        id: 12,
        name: "Termiz",
        centre: "Uchqizil",
        langitude: "37.229019",
        latitude: "67.276754",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Termiz",
      },
      {
        id: 13,
        name: "Uzun",
        centre: "Uzun",
        langitude: "38.168266",
        latitude: "68.182696",
        addressLine: "Oʻzbekiston, Surxondaryo viloyati, Uzun tumani",
      },
    ],
    langitude: "37.956731",
    latitude: "67.484031",
    addressLine: "Oʻzbekiston, Surxondaryo viloyati",
  },
  {
    id: 7,
    name: "Jizzax",
    regions: [
      {
        id: 1,
        name: "Arnasoy",
        centre: "G'oliblar",
        langitude: "40.569319",
        latitude: "67.831661",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Arnasoy tumani",
      },
      {
        id: 2,
        name: "Baxmal",
        centre: "Usmat",
        langitude: "39.750439",
        latitude: "67.864647",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Baxmal tumani",
      },
      {
        id: 3,
        name: "Do'stlik",
        centre: "Do'stlik",
        langitude: "40.524976",
        latitude: "68.032605",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Doʻstlik tumani, Doʻstlik",
      },
      {
        id: 4,
        name: "Forish",
        centre: "Yangiqishloq",
        langitude: "40.649427",
        latitude: "67.178451",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Forish tumani",
      },
      {
        id: 5,
        name: "G'allaorol",
        centre: "G'allaorol",
        langitude: "40.026722",
        latitude: "67.59182",
        addressLine:
          "Oʻzbekiston, Jizzax viloyati, Gʻallaorol tumani, Gʻallaorol",
      },
      {
        id: 6,
        name: "Sharof Rashidov",
        centre: "Uchtepa",
        langitude: "40.010594",
        latitude: "67.881491",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Sharof Rashidov tumani",
      },
      {
        id: 7,
        name: "Mirzacho'l",
        centre: "Gagarin",
        langitude: "40.699033",
        latitude: "68.093754",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Mirzachoʻl tumani",
      },
      {
        id: 8,
        name: "Paxtakor",
        centre: "Paxtakor",
        langitude: "40.310781",
        latitude: "67.956096",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Paxtakor",
      },
      {
        id: 9,
        name: "Yangiobod",
        centre: "Balandchaqir",
        langitude: "40.003196",
        latitude: "68.766296",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Yangiobod tumani",
      },
      {
        id: 10,
        name: "Zomin",
        centre: "Zomin",
        langitude: "39.895395",
        latitude: "68.341806",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Zomin tumani",
      },
      {
        id: 11,
        name: "Zafarobod",
        centre: "Zafarobod",
        langitude: "40.358744",
        latitude: "67.796762",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Zafarobod tumani",
      },
      {
        id: 12,
        name: "Zarbdor",
        centre: "Zarbdor",
        langitude: "40.156492",
        latitude: "68.17533",
        addressLine: "Oʻzbekiston, Jizzax viloyati, Zarbdor tumani",
      },
    ],
    langitude: "40.120288",
    latitude: "67.828508",
    addressLine: "Oʻzbekiston, Jizzax",
  },
  {
    id: 8,
    name: "Sirdaryo",
    regions: [
      {
        id: 1,
        name: "Oqoltin",
        centre: "Sardoba",
        langitude: "40.533352",
        latitude: "68.326184",
        addressLine: "Oʻzbekiston, Sirdaryo viloyati, Oqoltin tumani",
      },
      {
        id: 2,
        name: "Boyovut",
        centre: "Boyovut",
        langitude: "40.366096",
        latitude: "68.941144",
        addressLine: "Oʻzbekiston, Sirdaryo viloyati, Boyovut tumani",
      },
      {
        id: 3,
        name: "Guliston",
        centre: "Dehqonobod",
        langitude: "40.492764",
        latitude: "68.777165",
        addressLine: "Oʻzbekiston, Sirdaryo viloyati, Guliston",
      },
      {
        id: 4,
        name: "Xovos",
        centre: "Xovos",
        langitude: "40.230734",
        latitude: "68.713843",
        addressLine: "Oʻzbekiston, Sirdaryo viloyati, Xovos tumani",
      },
      {
        id: 5,
        name: "Mirzaobod",
        centre: "Navro'z",
        langitude: "40.451136",
        latitude: "68.633866",
        addressLine: "Oʻzbekiston, Sirdaryo viloyati, Mirzaobod tumani",
      },
      {
        id: 6,
        name: "Sayxunobod",
        centre: "Sayxun",
        langitude: "40.657411",
        latitude: "68.832043",
        addressLine: "Oʻzbekiston, Sirdaryo viloyati, Sayxunobod tumani",
      },
      {
        id: 7,
        name: "Sardoba",
        centre: "Paxtaobod",
        langitude: "40.544277",
        latitude: "68.413806",
        addressLine:
          "Oʻzbekiston, Sirdaryo viloyati, Oqoltin tumani, Sardoba shaharchasi",
      },
      {
        id: 8,
        name: "Sirdaryo",
        centre: "Sirdaryo",
        langitude: "40.838837",
        latitude: "68.664229",
        addressLine:
          "Oʻzbekiston, Sirdaryo viloyati, Sirdaryo tumani, Sirdaryo",
      },
    ],
    langitude: "40.838837",
    latitude: "68.664229",
    addressLine: "Oʻzbekiston, Sirdaryo viloyati, Sirdaryo tumani, Sirdaryo",
  },
  {
    id: 9,
    name: "Toshkent",
    regions: [
      {
        id: 1,
        name: "Bekobod",
        centre: "Zafar",
        langitude: "40.217699",
        latitude: "69.265795",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Bekobod",
      },
      {
        id: 2,
        name: "Bo'stonliq",
        centre: "G'azalkent",
        langitude: "41.571603",
        latitude: "69.939343",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Boʻstonliq tumani",
      },
      {
        id: 3,
        name: "Bo'ka",
        centre: "Bo'ka",
        langitude: "40.814272",
        latitude: "69.201305",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Boʻka tumani, Boʻka",
      },
      {
        id: 4,
        name: "Chinoz",
        centre: "Chinoz",
        langitude: "40.934806",
        latitude: "68.763304",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Chinoz tumani, Chinoz",
      },
      {
        id: 5,
        name: "Qibray",
        centre: "Qibray",
        langitude: "41.428701",
        latitude: "69.488343",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Qibray tumani",
      },
      {
        id: 6,
        name: "Ohangaron",
        centre: "Ohangaron",
        langitude: "40.91044",
        latitude: "69.64368",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Ohangaron",
      },
      {
        id: 7,
        name: "Oqqo'rg'on",
        centre: "Oqqo'rg'on",
        langitude: "40.878572",
        latitude: "69.046812",
        addressLine:
          "Oʻzbekiston, Toshkent viloyati, Oqqoʻrgʻon tumani, Oqqoʻrgʻon",
      },
      {
        id: 8,
        name: "Parkent",
        centre: "Parkent",
        langitude: "41.295008",
        latitude: "69.673504",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Parkent tumani, Parkent",
      },
      {
        id: 9,
        name: "Piskent",
        centre: "Piskent",
        langitude: "40.898104",
        latitude: "69.351153",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Piskent",
      },
      {
        id: 10,
        name: "Quyi chirchiq",
        centre: "Do'stobod",
        langitude: "40.934411",
        latitude: "68.997728",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Quyichirchiq tumani",
      },
      {
        id: 11,
        name: "O'rta Chirchiq",
        centre: "To'ytepa",
        langitude: "41.057024",
        latitude: "69.307782",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Oʻrtachirchiq tumani",
      },
      {
        id: 12,
        name: "Yangiyo'l",
        centre: "Gulbahor",
        langitude: "41.118933",
        latitude: "69.058544",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Yangiyoʻl",
      },
      {
        id: 13,
        name: "Yuqori Chirchiq",
        centre: "Yangibozor",
        langitude: "41.187381",
        latitude: "69.498081",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Yuqorichirchiq tumani",
      },
      {
        id: 14,
        name: "Zangiota",
        centre: "Keles",
        langitude: "41.260521",
        latitude: "69.085665",
        addressLine: "Oʻzbekiston, Toshkent viloyati, Zangiota tumani",
      },
    ],
    langitude: "41.311151",
    latitude: "69.279737",
    addressLine: "Oʻzbekiston, Toshkent",
  },
  {
    id: 10,
    name: "Namangan",
    regions: [
      {
        id: 1,
        name: "Chortoq",
        centre: "Chortoq",
        langitude: "41.077005",
        latitude: "71.814387",
        addressLine: "Oʻzbekiston, Namangan viloyati, Chortoq tumani, Chortoq",
      },
      {
        id: 2,
        name: "Chust",
        centre: "Chust",
        langitude: "41.002392",
        latitude: "71.226413",
        addressLine: "Oʻzbekiston, Namangan viloyati, Chust tumani, Chust",
      },
      {
        id: 3,
        name: "Kosonsoy",
        centre: "Kosonsoy",
        langitude: "41.254651",
        latitude: "71.544452",
        addressLine:
          "Oʻzbekiston, Namangan viloyati, Kosonsoy tumani, Kosonsoy",
      },
      {
        id: 4,
        name: "Mingbuloq",
        centre: "Jomasho'y",
        langitude: "40.772551",
        latitude: "71.366182",
        addressLine: "Oʻzbekiston, Namangan viloyati, Mingbuloq tumani",
      },
      {
        id: 5,
        name: "Namangan",
        centre: "Toshbuloq",
        langitude: "41.000078",
        latitude: "71.67257",
        addressLine: "Oʻzbekiston, Namangan viloyati, Namangan",
      },
      {
        id: 6,
        name: "Norin",
        centre: "Haqqulobod",
        langitude: "40.934309",
        latitude: "72.013768",
        addressLine: "Oʻzbekiston, Namangan viloyati, Norin tumani",
      },
      {
        id: 7,
        name: "Pop",
        centre: "Pop",
        langitude: "40.875109",
        latitude: "71.097199",
        addressLine: "Oʻzbekiston, Namangan viloyati, Pop tumani, Pop",
      },
      {
        id: 8,
        name: "To'raqo'rg'on",
        centre: "To'raqo'rg'on",
        langitude: "41.000793",
        latitude: "71.507181",
        addressLine:
          "Oʻzbekiston, Namangan viloyati, Toʻraqoʻrgʻon tumani, Toʻraqoʻrgʻon",
      },
      {
        id: 9,
        name: "Uchqo'rg'on",
        centre: "Uchqo'rg'on",
        langitude: "41.114592",
        latitude: "72.077584",
        addressLine:
          "Oʻzbekiston, Namangan viloyati, Uchqoʻrgʻon tumani, Uchqoʻrgʻon",
      },
      {
        id: 10,
        name: "Uychi",
        centre: "Uychi",
        langitude: "41.03907",
        latitude: "71.920298",
        addressLine: "Oʻzbekiston, Namangan viloyati, Uychi tumani",
      },
      {
        id: 11,
        name: "Yangiqo'rg'on",
        centre: "Yangiqo'rg'on",
        langitude: "41.279539",
        latitude: "71.719372",
        addressLine: "Oʻzbekiston, Namangan viloyati, Yangiqo’rg’on tumani",
      },
    ],
    langitude: "41.000078",
    latitude: "71.67257",
    addressLine: "Oʻzbekiston, Namangan viloyati, Namangan",
  },
  {
    id: 11,
    name: "Farg'ona",
    regions: [
      {
        id: 1,
        name: "Oltiariq",
        centre: "Oltiariq",
        langitude: "40.463302",
        latitude: "71.456543",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Oltiariq tumani",
      },
      {
        id: 2,
        name: "Bag'dod",
        centre: "Bag'dod",
        langitude: "40.49583",
        latitude: "71.219648",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Bagʻdod tumani",
      },
      {
        id: 3,
        name: "Beshariq",
        centre: "Beshariq",
        langitude: "40.43664",
        latitude: "70.606171",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Beshariq",
      },
      {
        id: 4,
        name: "Buvayda",
        centre: "Ibrat",
        langitude: "40.615242",
        latitude: "71.140965",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Buvayda tumani",
      },
      {
        id: 5,
        name: "Dang'ara",
        centre: "Dang'ara",
        langitude: "40.6331",
        latitude: "70.865021",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Dangʻara tumani",
      },
      {
        id: 6,
        name: "Farg'ona",
        centre: "Vodil",
        langitude: "40.38942",
        latitude: "71.783009",
        addressLine: "Oʻzbekiston, Fargʻona",
      },
      {
        id: 7,
        name: "Furqat",
        centre: "Navbahor",
        langitude: "40.50986",
        latitude: "70.760304",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Furqat tumani",
      },
      {
        id: 8,
        name: "Qo'shtepa",
        centre: "Langar",
        langitude: "40.53131",
        latitude: "71.61232",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Qoʻshtepa tumani",
      },
      {
        id: 9,
        name: "Quva",
        centre: "Quva",
        langitude: "40.523879",
        latitude: "72.068826",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Quva",
      },
      {
        id: 10,
        name: "Rishton",
        centre: "Rishton",
        langitude: "40.359273",
        latitude: "71.279746",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Rishton",
      },
      {
        id: 11,
        name: "So'x",
        centre: "Ravon",
        langitude: "40.038716",
        latitude: "71.066665",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Soʻx tumani",
      },
      {
        id: 12,
        name: "Toshloq",
        centre: "Toshloq",
        langitude: "40.513966",
        latitude: "71.823191",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Toshloq tumani",
      },
      {
        id: 13,
        name: "Uchko'prik",
        centre: "Uchko'prik",
        langitude: "40.523811",
        latitude: "71.043668",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Uchkoʻprik tumani",
      },
      {
        id: 14,
        name: "O'zbekiston",
        centre: "Yaypan",
        langitude: "40.38942",
        latitude: "71.783009",
        addressLine: "Oʻzbekiston, Fargʻona",
      },
      {
        id: 15,
        name: "Yozyovon",
        centre: "Yozyovon",
        langitude: "40.646341",
        latitude: "71.658754",
        addressLine: "Oʻzbekiston, Fargʻona viloyati, Yozyovon tumani",
      },
    ],
    langitude: "40.38942",
    latitude: "71.783009",
    addressLine: "Oʻzbekiston, Fargʻona",
  },
  {
    id: 12,
    name: "Andijon",
    regions: [
      {
        id: 1,
        name: "Andijon",
        centre: "Kuyganyor",
        langitude: "40.783368",
        latitude: "72.350654",
        addressLine: "Oʻzbekiston, Andijon",
      },
      {
        id: 2,
        name: "Asaka",
        centre: "Asaka",
        langitude: "40.642372",
        latitude: "72.246818",
        addressLine: "Oʻzbekiston, Andijon viloyati, Asaka tumani, Asaka",
      },
      {
        id: 3,
        name: "Baliqchi",
        centre: "Baliqchi",
        langitude: "40.855632",
        latitude: "71.951227",
        addressLine: "Oʻzbekiston, Andijon viloyati, Baliqchi tumani",
      },
      {
        id: 4,
        name: "Bo'z",
        centre: "Bo'z",
        langitude: "40.687334",
        latitude: "71.921403",
        addressLine:
          "Oʻzbekiston, Andijon viloyati, Boʻston tumani, Boʻz shaharchasi",
      },
      {
        id: 5,
        name: "Buloqboshi",
        centre: "Buloqboshi",
        langitude: "40.609033",
        latitude: "72.487683",
        addressLine: "Oʻzbekiston, Andijon viloyati, Buloqboshi tumani",
      },
      {
        id: 6,
        name: "Izboskan",
        centre: "Poytug'",
        langitude: "40.912178",
        latitude: "72.261506",
        addressLine: "Oʻzbekiston, Andijon viloyati, Izboskan tumani",
      },
      {
        id: 7,
        name: "Jalaquduq",
        centre: "Oxunboboyev",
        langitude: "40.718892",
        latitude: "72.642337",
        addressLine:
          "Oʻzbekiston, Andijon viloyati, Jalaquduq tumani, Jalaquduq",
      },
      {
        id: 8,
        name: "Xo'jaobod",
        centre: "Xo'jaobod",
        langitude: "40.670298",
        latitude: "72.560654",
        addressLine:
          "Oʻzbekiston, Andijon viloyati, Xoʻjaobod tumani, Xoʻjaobod",
      },
      {
        id: 9,
        name: "Qo'rg'ontepa",
        centre: "Qo'rg'ontepa",
        langitude: "40.730175",
        latitude: "72.759496",
        addressLine:
          "Oʻzbekiston, Andijon viloyati, Qoʻrgʻontepa tumani, Qoʻrgʻontepa",
      },
      {
        id: 10,
        name: "Marhamat",
        centre: "Marhamat",
        langitude: "40.503668",
        latitude: "72.33338",
        addressLine: "Oʻzbekiston, Andijon viloyati, Marhamat tumani, Marhamat",
      },
      {
        id: 11,
        name: "Oltinko'l",
        centre: "Oltinko'l",
        langitude: "40.777188",
        latitude: "72.195165",
        addressLine: "Oʻzbekiston, Andijon viloyati, Oltinkoʻl tumani",
      },
      {
        id: 12,
        name: "Paxtaobod",
        centre: "Paxtaobod",
        langitude: "40.932504",
        latitude: "72.496837",
        addressLine:
          "Oʻzbekiston, Andijon viloyati, Paxtaobod tumani, Paxtaobod",
      },
      {
        id: 13,
        name: "Shahrixon",
        centre: "Shahrixon",
        langitude: "40.711598",
        latitude: "72.05094",
        addressLine:
          "Oʻzbekiston, Andijon viloyati, Shahrixon tumani, Shahrixon",
      },
      {
        id: 14,
        name: "Ulug'nor",
        centre: "Oqoltin",
        langitude: "40.789588",
        latitude: "71.703436",
        addressLine: "Oʻzbekiston, Andijon viloyati, Ulugʻnor tumani",
      },
    ],
    langitude: "40.783368",
    latitude: "72.350654",
    addressLine: "Oʻzbekiston, Andijon",
  },
  {
    id: 13,
    name: "Toshkent shahri",
    regions: [
      {
        id: 1,
        name: "Bektemir",
        langitude: "41.233273",
        latitude: "69.334696",
        addressLine: "Oʻzbekiston, Toshkent, Bektemir tumani",
      },
      {
        id: 2,
        name: "Chilonzor",
        langitude: "41.28141",
        latitude: "69.212668",
        addressLine: "Oʻzbekiston, Toshkent, Chilonzor tumani",
      },
      {
        id: 3,
        name: "Yashnobod",
        langitude: "41.283463",
        latitude: "69.339789",
        addressLine: "Oʻzbekiston, Toshkent, Yashnobod tumani",
      },
      {
        id: 4,
        name: "Mirobod",
        langitude: "41.292562",
        latitude: "69.285683",
        addressLine: "Oʻzbekiston, Toshkent, Mirobod tumani",
      },
      {
        id: 5,
        name: "Mirzo Ulug'bek",
        langitude: "41.326213",
        latitude: "69.326916",
        addressLine: "Oʻzbekiston, Toshkent, Mirzo Ulugʻbek tumani",
      },
      {
        id: 6,
        name: "Sergeli",
        langitude: "41.23507",
        latitude: "69.247352",
        addressLine: "Oʻzbekiston, Toshkent, Sergeli tumani",
      },
      {
        id: 7,
        name: "Shayxontohur",
        langitude: "41.317646",
        latitude: "69.230581",
        addressLine: "Oʻzbekiston, Toshkent, Shayxontohur tumani",
      },
      {
        id: 8,
        name: "Olmazor",
        langitude: "41.35435",
        latitude: "69.223358",
        addressLine: "Oʻzbekiston, Toshkent, Olmazor tumani",
      },
      {
        id: 9,
        name: "Uchtepa",
        langitude: "41.295991",
        latitude: "69.175191",
        addressLine: "Oʻzbekiston, Toshkent, Uchtepa tumani",
      },
      {
        id: 10,
        name: "Yakkasaroy",
        langitude: "41.286004",
        latitude: "69.253748",
        addressLine: "Oʻzbekiston, Toshkent, Yakkasaroy tumani",
      },
      {
        id: 11,
        name: "Yunusobod",
        langitude: "41.364657",
        latitude: "69.287696",
        addressLine: "Oʻzbekiston, Toshkent, Yunusobod tumani",
      },
    ],
    langitude: "41.311151",
    latitude: "69.279737",
    addressLine: "Oʻzbekiston, Toshkent",
  },
];
