export const texts = {
  main_text: "main_text",
  weather_info: "weather_info",
  weekly: "weekly",
  half_mounth: "half_mounth",
  mounth: "mounth",
  around: "around",
  choose_region: "choose_region",
  location: "location",
  district: "district",
  choose_district: "Tumanni tanlang",
  region: "region",
  profile: "profile",
  main_menu: "main_menu",
  language: "language",
  introduction: "introduction",
  go_back: "go_back",
  skip_btn: "skip_btn",
};
