export const texts = {
  main_text: "main_text",
  weather_info: "weather_info",
  weekly: "weekly",
  hourly: "hourly",
  current_time: "current_time",
  choose_region: "choose_region",
  location: "location",
  change_location: "change_location",
  district: "district",
  choose_district: "choose_district",
  region: "region",
  profile: "profile",
  main_menu: "main_menu",
  language: "language",
  introduction: "introduction",
  go_back: "go_back",
  skip_btn: "skip_btn",
};
